### PR TITLE
Fix name for docker ignore file

### PR DESCRIPTION
**Pull request by daniel-zullo-sociomantic**
The right name is `.dockerignore` according to the documentation.
https://docs.docker.com/engine/reference/builder/#dockerignore-file

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
How did you notice this?

**Comment by daniel-zullo-sociomantic** [comment]
I was checking the patch #58 to apply a similar one into the `dmqnode`. There I saw the file was moved wrongly (please see https://github.com/sociomantic-tsunami/dhtnode/pull/58/files#diff-1222218b2c7627621d730b7ec5d77120) and checked the docker documentation to verify it.

**Comment by gavin-norman-sociomantic** [comment]
Mm, so you mean Luca's PR renamed that file by mistake? (How do you know it was a mistake?)

**Comment by gavin-norman-sociomantic** [comment]
(Sorry for being pedantic. It's just an area of the code that I know virtually nothing about, so don't want to merge blindly.)

**Comment by daniel-zullo-sociomantic** [comment]
Well docker only recognises `.dockerignore` as stated in the documentation.

Then beaver checks for it here https://github.com/sociomantic-tsunami/beaver/blob/v0.6.x/bin/beaver-install#L21-L26

But there is some magic in beaver that check for both files `dockerignore` and `.dockerignore` if the context is provided 
https://github.com/sociomantic-tsunami/beaver/blob/v0.6.x/bin/beaver-install#L37-L38
Anyway that's just a hack....

**Comment by daniel-zullo-sociomantic** [comment]
> Mm, so you mean Luca's PR renamed that file by mistake? (How do you know it was a mistake?)

I think Mihails did it. It works only because of beaver workaround

**Comment by daniel-zullo-sociomantic** [comment]
Found the reason of the hack in beaver :)
https://github.com/sociomantic-tsunami/beaver/pull/49

**Comment by daniel-zullo-sociomantic** [comment]
```
beaver install: Support multiple Dockerfile contexts

Sometimes is useful to have multiple different docker contexts for
a project. The most typical case is having one (`beaver.`)`Dockerfile`
for building a project (with the build dependencies), and another one to
run the project (with the runtime dependencies). Since Docker doesn't
support specifying a `.dockerignore` file yet, we overcome this
limitation in beaver.

To use multiple build contexts, you can specify the variable
`BEAVER_DOCKER_CONTEXT` to point to a directory that will contain your
`Dockerfile` or `beaver.Dockerfile` and possibly a `build` script
(equivalent to the `docker/build` script in normal builds) and/or
a `dockerignore` (`.dockerignore is also accepted but `dockerignore`
will take precedence), which will be copied to the current working
directory as `.dockerignore`.
```

The file `dockerignore` will take precedence so it seems this was done deliberately. Closing this patch then

**Pull request closed without merging**
