### PR TITLE
Cherries from v1.9.7 - v1.9.10

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**
The commits in this PR were made against the old v1.9.x branch in the private dhtnode repo. Bringing them into v1.10.x here.

Notes:
* v1.9.9: Commit 44400b7d1e67130433bed737e80e03d49bd6135a (in the private repo) is included in the PR but reverted. The bug that it was investigating has since been fixed. (Requires a dhtproto submodule update. See #32.)
* v1.9.10: Commit fd1c23f9359d7e72d91b3acc0a4cbaa49525896e (in the private repo) was left out. It updated to the latest patch releases of submodules used by v1.9.x. This will be replaced by #32.

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
Suggestion for reviewers: maybe check against the private repo, to confirm that I've not missed out any commits.

**Comment by nemanja-boric-sociomantic** [comment]
I've cross checked the private repo and they are all here. Last commits in private's master is already in the initial import, and same for tag v1.9.6. I agree about reverting that one commit.

**Comment by gavin-norman-sociomantic** [comment]
Hmm. Test failures:
```
Step 1/3 : FROM sociomantictsunami/dlang:trusty-v2
trusty-v2: Pulling from sociomantictsunami/dlang
...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by nemanja-boric-sociomantic** [comment]
I bet Travis is having problems again.

**Comment by gavin-norman-sociomantic** [comment]
Yeah, seems like it :(

**Comment by gavin-norman-sociomantic** [comment]
Green now. I think we can put the failures down to CI flakiness (unfortunately).

**Comment by gavin-norman-sociomantic** [comment]
Auto merging. This is code that's already been reviewed in v1.9.x and was approved by Nemanja.

**Pull request merged**
