### PR TITLE
[neptune] Update submodules

### PR DESCRIPTION
**Pull request by jenkins-sociomantic**
This PR has been automatically created by *neptune-autopr* and
updates the following submodules:

* **ocean** from version **v4.1.6** to version **v4.2.1** ([Release notes](https://github.com/sociomantic-tsunami/ocean/releases/tag/v4.2.1), [Changed commits](https://github.com/sociomantic-tsunami/ocean/compare/v4.1.6...v4.2.1))

You can modify this behavior using your `.neptune.yml` file
as described in the [documentation](https://github.com/sociomantic-tsunami/neptune/blob/master/doc/neptune-metadata.rst#automatic-update-prs).

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
Hm, looks like ocean ugrade has required linking ebtree to new binaries :/ FYI @gavin-norman-sociomantic  @leandro-lucarella-sociomantic

**Comment by gavin-norman-sociomantic** [comment]
Hmm... is this a breaking change in ocean v4.2.x somehow?

**Comment by mihails-strasuns-sociomantic** [comment]
Could be though I see no commits that introduce new ebtree dependency. Will need to bisect

**Comment by leandro-lucarella-sociomantic** [comment]
This is strange. Cachalot version didn't change, right? (Just to discard any changes in the toolchain itself)

**Comment by mihails-strasuns-sociomantic** [comment]
Works for me when I build this PR locally

**Comment by mihails-strasuns-sociomantic** [comment]
Ah, it looks like it starts with some beaver problem @leandro-lucarella-sociomantic 

```
43.81s$ beaver dlang install
submodules/beaver/bin/dlang/install: 29: test: test: unexpected operator
```

**Comment by mihails-strasuns-sociomantic** [comment]
Tracked ebtree bit - it is a linking regression from https://github.com/sociomantic-tsunami/ocean/pull/533 (adding taskext support to cli apps). Not sure how do we want to handle it in context of neptune :x

**Comment by mihails-strasuns-sociomantic** [comment]
It starts to import scheduler which uses ebtree for timers.

**Comment by nemanja-boric-sociomantic** [comment]
I made this PR https://github.com/sociomantic-tsunami/dhtnode/pull/126 (I shouldn't have closed the Neptune auropr) yesterday on the basis that ocean does specify ebtree as required library. I'm not sure if we really want to disallow requiring ebtree linking- half of the ocean depend on it and that would mean that we can't use data structures, for features in minor releases, because we might break something.

IMHO, not linking against libraries already required is a bug in some definitions of bug.

**Comment by nemanja-boric-sociomantic** [comment]
Done in #126

**Pull request closed without merging**
