### PR TITLE
[neptune] Update submodules

### PR DESCRIPTION
**Pull request by jenkins-sociomantic**
This PR has been automatically created by *neptune-autopr* and
updates the following submodules:

* **ocean** from version **v4.1.6** to version **v4.2.1** ([Release notes](https://github.com/sociomantic-tsunami/ocean/releases/tag/v4.2.1), [Changed commits](https://github.com/sociomantic-tsunami/ocean/compare/v4.1.6...v4.2.1))

You can modify this behavior using your `.neptune.yml` file
as described in the [documentation](https://github.com/sociomantic-tsunami/neptune/blob/master/doc/neptune-metadata.rst#automatic-update-prs).

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
This triggers linking problems with ebtree. Is this expected?

**Comment by nemanja-boric-sociomantic** [comment]
Highly unexpected, because dhtnode is linked with ebtree. https://github.com/sociomantic-tsunami/dhtnode/blob/master/Build.mak#L18

**Comment by nemanja-boric-sociomantic** [comment]
Oh, but it's the `tcmcli` target that is not using this.

**Comment by nemanja-boric-sociomantic** [comment]
https://github.com/sociomantic-tsunami/dhtnode/pull/126

**Pull request closed without merging**
