### PR TITLE
Remove trusty support and update beaver to v0.2.2

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> 
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

It didn't take that long when testing locally :(

**Comment by leandro-lucarella-sociomantic** [comment]
```
time docker run --rm -v /home/luca:/home/luca -v /home/luca/devel/dhtnode:/home/luca/devel/dhtnode -w /home/luca/devel/dhtnode -u 1000 -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e USER -e HOME -e DEBIAN_FRONTEND -e RAILS_ENV -e RACK_ENV -e MERB_ENV -e JRUBY_OPTS -e JAVA_HOME -e CI -e CONTINUOUS_INTEGRATION -e TRAVIS -e DIST -e DC -e DVER beaver make -rj2 -B all test DC=dmd1 DIST=xenial F=production DVER=1
   rdmd build/production/bin/dhtnode
   rdmd build/production/bin/dhtdump
   rdmd build/production/bin/dhtredist
   rdmd build/production/bin/tcmcli
   rdmd build/production/bin/dhtperformance
   gen build/production/tmp/allunittests.d
   rdmd build/production/tmp/test-dhttest
   rdmd build/production/tmp/allunittests
   run build/production/tmp/test-dhttest
   run build/production/tmp/allunittests

real	0m53.600s
user	0m0.018s
sys	0m0.005s
```

Can anybody check how it goes for you?

**Comment by nemanja-boric-sociomantic** [comment]
Strange, dhtnode test hangs locally for me.  It hangs on

```
[turtle    ] Testing 'Listen stops after removing channel' ...
```

cc @gavin-norman-sociomantic

**Comment by gavin-norman-sociomantic** [comment]
Oh dear :( @nemanja-boric-sociomantic do you mean it hangs for you after updating beaver? Or it just always hangs?

**Comment by nemanja-boric-sociomantic** [comment]
It hangs on the latest master :(. Could you try reproducing?

**Comment by gavin-norman-sociomantic** [comment]
Works for me.

**Comment by nemanja-boric-sociomantic** [comment]
```
nemanjaboric@labs-129:/home/nemanjaboric/work/tsunami/dhtnode  git:(master) $ PAGER= git show --quiet
commit 23a8da3b142b5936a6574e3583db3b4d9330ae24 (HEAD -> master, upstream/master)
Author: Mathias Lang <mathias.lang@sociomantic.com>
Date:   Tue Sep 19 17:21:09 2017 +0200

    Replace last usage of Layout_Tango with Formatter
nemanjaboric@labs-129:/home/nemanjaboric/work/tsunami/dhtnode  git:(master) $ git submodule 
 f60fd6c3a0c23570cc8e9fa44e694173bac09396 submodules/beaver (v0.1.2)
 a972c8c8b1bb516fe371b02ea5a75f68f462c90f submodules/dhtproto (v13.0.0)
 0661a593e1a81b17a605a449e43b46ffc1c1398f submodules/makd (v1.9.0)
 2f23ce9f0e7098fa06e079cdbb242eebfecf2fa8 submodules/ocean (v3.1.2)
 16704749b036118e288f46d3bdde7ac1e30b41dc submodules/swarm (v4.0.2)
 a319c42a6ea17e6f1c73d43db16db693de05f0a7 submodules/turtle (v8.0.0)

nemanjaboric@labs-129:/home/nemanjaboric/work/tsunami/dhtnode  git:(master) $ make clean
   rm build

nemanjaboric@labs-129:/home/nemanjaboric/work/tsunami/dhtnode  git:(master) $ make test
   gen build/devel/tmp/allunittests.d
   rdmd build/devel/tmp/allunittests
   run build/devel/tmp/allunittests
   rdmd build/devel/bin/dhtnode
   rdmd build/devel/tmp/test-dhttest
   run build/devel/tmp/test-dhttest
```

**Comment by gavin-norman-sociomantic** [comment]
```
gavinnorman@labs-080:~/devel/dhtnode-tsunami:master %=$ git show --quiet
commit 23a8da3b142b5936a6574e3583db3b4d9330ae24
Author: Mathias Lang <mathias.lang@sociomantic.com>
Date:   Tue Sep 19 17:21:09 2017 +0200

    Replace last usage of Layout_Tango with Formatter
gavinnorman@labs-080:~/devel/dhtnode-tsunami:master %=$ git submodule 
 f60fd6c3a0c23570cc8e9fa44e694173bac09396 submodules/beaver (v0.1.2)
 a972c8c8b1bb516fe371b02ea5a75f68f462c90f submodules/dhtproto (v13.0.0)
 0661a593e1a81b17a605a449e43b46ffc1c1398f submodules/makd (v1.9.0)
 2f23ce9f0e7098fa06e079cdbb242eebfecf2fa8 submodules/ocean (v3.1.2)
 16704749b036118e288f46d3bdde7ac1e30b41dc submodules/swarm (v4.0.2)
 a319c42a6ea17e6f1c73d43db16db693de05f0a7 submodules/turtle (v8.0.0)
gavinnorman@labs-080:~/devel/dhtnode-tsunami:master %=$ make clean
   rm build
gavinnorman@labs-080:~/devel/dhtnode-tsunami:master %=$ make test
   gen build/devel/tmp/allunittests.d
   rdmd build/devel/tmp/allunittests
   run build/devel/tmp/allunittests
   rdmd build/devel/bin/dhtnode
   rdmd build/devel/tmp/test-dhttest
   run build/devel/tmp/test-dhttest
gavinnorman@labs-080:~/devel/dhtnode-tsunami:master %=$ 
```

**Comment by nemanja-boric-sociomantic** [comment]
... aaaand my ability to reproduce the bug is suddenly gone :(.

**Comment by nemanja-boric-sociomantic** [comment]
It's very interesting that the actual output of the `make test` doesn't match what's actually running @leandro-lucarella-sociomantic .

See my output:

```
nemanjaboric@labs-129:/home/nemanjaboric/work/tsunami/dhtnode  git:(1f6bf3e*) $ time docker run --rm -v $PWD:/home/luca/devel/dhtnode -w /home/luca/devel/dhtnode -u 1000 -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e USER -e HOME -e DEBIAN_FRONTEND -e RAILS_ENV -e RACK_ENV -e MERB_ENV -e JRUBY_OPTS -e JAVA_HOME -e CI -e CONTINUOUS_INTEGRATION -e TRAVIS -e DIST -e DC -e DVER beaver make -rj2 -B all test DC=dmd1 DIST=xenial F=production DVER=1
   rdmd build/production/bin/dhtdump
   rdmd build/production/bin/dhtnode
   rdmd build/production/bin/dhtredist
   rdmd build/production/bin/tcmcli
   rdmd build/production/bin/dhtperformance
   gen build/production/tmp/allunittests.d
   rdmd build/production/tmp/test-dhttest
   rdmd build/production/tmp/allunittests
   run build/production/tmp/test-dhttest
   run build/production/tmp/allunittests

```

You would guess that we're actually running `allunittests` program at this point. However it's `test-dhttest` that's running:

```
nemanjaboric@labs-129:/home/nemanjaboric/work/tsunami/dhtnode  git:(1f6bf3e*) $ ps aux | grep test-dhttest
nemanja+  7404  0.0  0.0   4508   744 ?        S    13:49   0:00 /bin/sh -c printf  '   \033[00;33m%s\033[00m %s\n\033[00;31m' 'run' 'build/production/tmp/test-dhttest' ; /home/luca/devel/dhtnode/build/production/tmp/test-dhttest   ; r=$? ; printf '\033[00m' ; exit $r
nemanja+  7405  0.1  0.3  44204 25460 ?        S    13:49   0:00 /home/luca/devel/dhtnode/build/production/tmp/test-dhttest
nemanja+  8250  0.0  0.0  15776  1036 pts/2    S+   13:52   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn test-dhttest
```

Are targets run in parallel?

**Comment by nemanja-boric-sociomantic** [comment]
Yeah, it seems that the test targets are running in parallel. I never knew!

```
/home/luca/devel/dhtnode/build/production/tmp/test-dhttest  <---- starting test target
[turtle    ] Testing '/home/luca/devel/dhtnode/build/production/bin/dhtnode'
[turtle    ] Started test runner task
[turtle    ] $ rm -rf /home/luca/devel/dhtnode/build/production/tmp/sandbox-dhtnode/
[turtle    ] $ mkdir /home/luca/devel/dhtnode/build/production/tmp/sandbox-dhtnode/
[turtle    ] Changing working dir to '/home/luca/devel/dhtnode/build/production/tmp/sandbox-dhtnode/'
[turtle    ] $ mkdir ./bin
[turtle    ] $ mkdir ./etc
[turtle    ] $ mkdir ./log
[turtle    ] $ install -m755 /home/luca/devel/dhtnode/build/production/bin/dhtnode ./bin/
[turtle    ] $ dirname /home/luca/devel/dhtnode/build/production/tmp/sandbox-dhtnode/etc/config.ini
[turtle    ] $ mkdir -p /home/luca/devel/dhtnode/build/production/tmp/sandbox-dhtnode/etc

[turtle    ] $ cp -r /home/luca/devel/dhtnode/test/dhttest/etc/config.ini /home/luca/devel/dhtnode/build/production/tmp/sandbox-dhtnode/etc/config.ini
[turtle    ] Temporary sandbox created at '/home/luca/devel/dhtnode/build/production/tmp/sandbox-dhtnode/'
[turtle    ] pid 620 : 'bin/dhtnode '
[turtle    ] Tested application started.
[turtle    ] Testing 'Handshake / Sanity' ...
[turtle    ] resetting the environment requested
[turtle    ] Testing 'Put followed by Get' ...
[turtle    ] resetting the environment requested
[turtle    ] Testing 'Get for non-existent entry' ...
[turtle    ] resetting the environment requested
[turtle    ] Testing 'GetAll for predefined data' ...
[turtle    ] resetting the environment requested
[turtle    ] Testing 'Removing channel' ...
[turtle    ] resetting the environment requested
[turtle    ] Testing 'Listen stops after removing channel' ... <---- this tests hangs here!
sed -i '\|^ */home/luca/devel/dhtnode/build/production/include/Version.d.*$|d' /home/luca/devel/dhtnode/build/production/tmp/allunittests.mak <---- running unittests target! 
/home/luca/devel/dhtnode/build/production/tmp/allunittests  -v -s  -p dhtredist. -p dhtperformance. -p dhtnode. -p tcmcli.  
allunittests: unit tests started
allunittests: dhtnode.storage.StorageChannels: testing ... PASS [1us, 0 bytes (123632 -> 123632)]
allunittests: dhtnode.config.HashRangeConfig: testing ... PASS [20us, 800 bytes (123648 -> 124448)]
allunittests: dhtredist.Redist: testing ... PASS [307.1ms, 750496 bytes (123648 -> 874144)]
allunittests: dhtnode.storage.DumpManager: testing ... PASS [571us, 732672 bytes (123648 -> 856320)]
allunittests: dhtnode.node.RedistributionProcess: testing ... PASS [237us, 8784 bytes (123648 -> 132432)]
allunittests: dhtnode.storage.StorageEngine: testing ... PASS [1us, 0 bytes (123648 -> 123648)]
allunittests: 6 modules passed, 0 failed, 0 with errors, 37 without unittests [317.3ms]
touch /home/luca/devel/dhtnode/build/production/tmp/allunittests.stamp 

# at this point the first test target still runs.
```

**Comment by leandro-lucarella-sociomantic** [comment]
So, do you know what the problem is? 2 tests working concurrently over the same files?

**Comment by nemanja-boric-sociomantic** [comment]
No, I'm still investigating it: #25. However I don't think it's related to this PR.

**Comment by nemanja-boric-sociomantic** [comment]
Fixed in: https://github.com/sociomantic-tsunami/dhtnode/pull/29

**Comment by nemanja-boric-sociomantic** [comment]
@leandro-lucarella-sociomantic you can rebase this on the latest master and it should pass the tests.

**Comment by leandro-lucarella-sociomantic** [comment]
Updated and :tada: 

Thanks @nemanja-boric-sociomantic !

**Pull request merged**
