### PR TITLE
[DOCKER] Use Docker recommends for application execution.

### PR DESCRIPTION
**Pull request by camilo-schoeningh-sociomantic**
As we want our application to get PID 1, to make sure it responds to
SIGTERM signals.

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint

FYI @mihails-strasuns

### CODE REVIEW

**Comment by mihails-strasuns** [comment]
I recommend using `docker run --init` instead of (one of many) workarounds with an entry point. Compose example:

```yml
version: '2.2'
services:
  dhtnode:
    image: sociomantic/dhtnode
    init: true
```

**Comment by nemanja-boric-sociomantic** [comment]
Sadly, Kubernetes doesn't support that IIRC.

**Comment by camilo-schoeningh-sociomantic** [comment]
This is what I am worried about ..

**Comment by nemanja-boric-sociomantic** [comment]
But I think the entry point here is what should be done - this usecase is well documented (could you link the documentation @camilo-schoeningh-sociomantic ?)

**Comment by camilo-schoeningh-sociomantic** [comment]
For sure. I will update it on the top. But here maybe some interesting quotes:

> CMD should rarely be used in the manner of CMD [“param”, “param”] in conjunction with ENTRYPOINT, unless you and your expected users are already quite familiar with how ENTRYPOINT works.

source: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#cmd

**Comment by mihails-strasuns** [comment]
> Sadly, Kubernetes doesn't support that IIRC

That is.. bad :/ I have been looking into existing practices for setting up proper init process in docker and that was rather convoluted problem to workaround manually.

> But I think the entry point here is what should be done

I don't think so. PID 1 is supposed to be init process - and dhtnode is definitely not capable of acting as such.

**Comment by mihails-strasuns** [comment]
So, for example, after this change `docker run --rm -it sociomantic/dhtnode /bin/bash` is likely to stop working.

**Comment by camilo-schoeningh-sociomantic** [comment]
Well, I am not sure. But you could use the docker image like a binary. If bash is not working, we could use the postgresql approach which is mentioned in the example.

**Comment by mihails-strasuns** [comment]
How about we instead build one of mini-inits as part of `sociomantic-tsunami/runtimebase` image?

**Comment by camilo-schoeningh-sociomantic** [comment]
> But you could use the docker image like a binary.

And IMHO this is welcomed by a couple of devs here for testing their applications without taking so much care of dht docker deployement.

**Comment by mihails-strasuns** [comment]
Like https://github.com/Yelp/dumb-init

**Comment by camilo-schoeningh-sociomantic** [comment]
@mihails-strasuns thanks! Gonna read it. Do we want to change to slack instead or is this needed for documentation? Maybe #docker channel?

**Comment by mihails-strasuns** [comment]
Sure, I will hop in.

**Comment by mihails-strasuns** [comment]
Also while I remember - https://github.com/sociomantic-tsunami/dhtnode/pull/158 :D

**Pull request closed without merging**
