### PR TITLE
[WIP] Update Makd to v2.0.1

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
Requires #27.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
This is failing because turtle uses the old `Version.versionInfo` (removed in MakD v2), which is a bit unfortunate as usually MakD shouldn't introduce inter-dependencies. I wonder if this dependency is really necessary or if it could be removed. The version info is just a `string[string[]]` and in ocean we use that to avoid this issue. Maybe turtle should do the same. /cc @mihails-strasuns-sociomantic

**Comment by leandro-lucarella-sociomantic** [comment]
BTW, by changing turtle to continue trying this PR, I get a test error.

**Comment by mihails-strasuns-sociomantic** [comment]
Upgrading turtle to next minor version should fix it. I added compatibility layer some time ago.

**Comment by mihails-strasuns-sociomantic** [comment]
(7.1.x or 8.1.x)

**Comment by mihails-strasuns-sociomantic** [comment]
Ping @leandro-lucarella-sociomantic

**Comment by leandro-lucarella-sociomantic** [comment]
Updated.

**Comment by leandro-lucarella-sociomantic** [comment]
Arrrggghhh! This damn error got me crazy. I spent a long while until I figured out the problem was the `module` declaration lacking `integrationtest` as the top-level package.
```
/home/travis/build/sociomantic-tsunami/dhtnode/build/devel/tmp/allunittests.d(52): Error: module dhttest.main from file integrationtest/dhttest/main.d conflicts with another module main from file integrationtest/dhttest/main.d
```
https://travis-ci.org/sociomantic-tsunami/dhtnode/jobs/289565206#L746

I think it should be mentioned in the Makd v2 release notes.

**Comment by leandro-lucarella-sociomantic** [comment]
Now (locally at least) I get some test errors :(

**Comment by leandro-lucarella-sociomantic** [comment]
> I think it should be mentioned in the Makd v2 release notes.

It is there :(

I guess I missed it because when I followed the guide I didn't get to that error...

**Comment by leandro-lucarella-sociomantic** [comment]
```
   run build/devel/tmp/test-dhttest

[turtle    ] Unexpected failure in test runner!

[turtle    ] turtle.Exception.TurtleException: `cp -r /home/travis/build/sociomantic-tsunami/dhtnode/test/dhttest/etc/config.ini /home/travis/build/sociomantic-tsunami/dhtnode/build/devel/tmp/sandbox-dhtnode/etc/config.ini` has failed (./submodules/turtle/src/turtle/env/Shell.d:61)
```

**Comment by Burgos** [comment]
Just change `DhtTestRunner.copyFiles` in `integrationtests/dhttest/main.d` to copy file to new location.

**Comment by mihails-strasuns-sociomantic** [comment]
> Arrrggghhh! This damn error got me crazy.

You obviously don't code in D often :) It is somewhat widely known kind of error, triggers any time `module` statement mismatches or gets duplicated.

**Comment by leandro-lucarella-sociomantic** [comment]
> You obviously don't code in D often :)

Obviously. I'd like to be able to code a bit more from time to time :(

**Comment by leandro-lucarella-sociomantic** [comment]
> It is somewhat widely known kind of error, triggers any time module statement mismatches or gets duplicated.

Yeah, for some reason I misread the error and was thinking it was a "duplicate main" error, which I got quite often when upgrading to MakD, and what my lazy brain was expecting...

**Comment by mihails-strasuns-sociomantic** [comment]
Still missing fix (https://github.com/sociomantic-tsunami/dhtnode/pull/28#issuecomment-337818732)

**Comment by leandro-lucarella-sociomantic** [comment]
> Just change DhtTestRunner.copyFiles in integrationtests/dhttest/main.d to copy file to new location.

I don't get it, different to what? There is only one integration test.

**Comment by nemanja-boric-sociomantic** [comment]
This line:

https://github.com/leandro-lucarella-sociomantic/dhtnode/blob/811f0103eee7ac5b8db899732a589d62f4440385/integrationtest/dhttest/main.d#L45

should be

```
        return [CopyFileEntry("/integrationtests/dhttest/etc/config.ini", "etc/config.ini")];
```

not

```
        return [CopyFileEntry("/test/dhttest/etc/config.ini", "etc/config.ini")];
```

**Comment by mihails-strasuns-sociomantic** [comment]
(or just don't store artifacts in `test` folder :P)

**Comment by leandro-lucarella-sociomantic** [comment]
Updated :crossed_fingers: :crossed_fingers:  (this time it worked locally :) )

**Pull request merged**
